language: php

php:
  - "7.2"

addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client

cache:
  directories:
    - src/vendor
    - src/node_modules

services:
  - mysql

before_script:
  - cd src
  - cp .env.ci .env
  - composer install --no-interaction --prefer-dist
  - npm install
  - npm run production
  - php artisan key:generate
  - php artisan migrate

script:
  - ./vendor/bin/phpstan analyse -l max app config tests bootstrap --no-interaction --no-progress
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)