language: php

php:
  - 7.2

addons:
  mariadb: '10.0'

sudo: false

before_script:
  - cp .env.ci .env
  - mysql -e 'create database pcb;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/354631412084637697/p93voigsxa85Po2GGNbZIQJA2DWXgexRM-lClCWrxKN-jMazfrRx6w-aZ229LS5QSTqE/github
    on_success: change  # default: always
    on_failure: always  # default: always
    on_start: change    # default: never
    on_cancel: always   # default: always
    on_error: always    # default: always