language: php
php:
  - '7.2'

cache:
  directories:
    - src/support/packages/vendor

services:
  - mysql

before_script:
  - cd src
  - cp .env.ci .env
  - composer install --no-interaction
  - npm install
  - npm run production
  - php artisan key:generate
  - php artisan migrate

script:
  - support/packages/vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "curl https://projectcitybuild.com/deploy?key=$DEPLOY_KEY"