branches:
  only:
  - master
  - feat/docker
  - dev/travis

language: php
php:
  - '7.1'

cache:
  directories:
    - src/vendor

services:
  - mysql

before_script:
  # disable xdebug since we're not generating coverage reports
  - phpenv config-rm xdebug.ini

  - cd src
  - cp .env.ci .env
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

after_success:
  - "curl https://www.projectcitybuild.com/deploy?key=$DEPLOY_KEY"