branches:
  only:
  - master
  - feat/docker
  - dev/travis

language: php
php:
  - '7.1'

cache:
  directories:
    - node_modules
    - vendor

services:
  - mysql

before_script:
  - cd src
  - cp .env.ci .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

after_success:
  # TODO: push to server