version: '3'

services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/containers/php-fpm/Dockerfile
        volumes:
            - "./:/var/www/html"
        networks:
            - pcb-web
        links:
          - "mariadb:db"
        depends_on:
            - mariadb
#            - redis

    nginx:
        build:
            context: .
            dockerfile: docker/containers/nginx/Dockerfile
        ports:
          - "80:80"
          - "443:443"
        links:
          - "php-fpm:pcb-laravel"
        networks:
          - pcb-web
        depends_on:
          - php-fpm

    mariadb:
        image: "mariadb:10.5"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "mysql:/var/lib/mysql"
        networks:
            - pcb-web

#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'redis:/data'
#        networks:
#            - pcb-web
#
#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - 1025:1025
#            - 8025:8025
#        networks:
#            - pcb-web

networks:
    pcb-web:
        driver: bridge

volumes:
    mysql:
        driver: local
#    redis:
#        driver: local
