version: '3'

services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                ENV: "PROD"
        networks:
            - pcb-web
        links:
            - "mariadb:db"
            - "redis:redis"
            - "mailhog:mailhog"
        depends_on:
            - mariadb
            - redis
            - mailhog

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        links:
            - "php-fpm:pcb-laravel"
        networks:
            - pcb-web
        depends_on:
            - php-fpm

    mariadb:
        image: "mariadb:10.5"
        ports:
            - "3306:3306"
        volumes:
            - "mysql:/var/lib/mysql"
        networks:
            - pcb-web

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis:/data'
        networks:
            - pcb-web

networks:
    pcb-web:
        driver: bridge

volumes:
    mysql:
        driver: local
    redis:
        driver: local
