version: '3'
services:

  nginx:
    build: 
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./storage/www:/var/www/html
    links:
      - php-fpm

  php-fpm:
    build: 
      context: .
      dockerfile: containers/php-fpm/Dockerfile
    ports:
      - "3000:3000"   # browser sync
      - "3001:3001"   # browser sync
    volumes:
      - ./storage/www:/var/www/html   # overwrite our baked-in source code with a mounted volume
    links:
      - redis
      - database

  redis:
    image: redis:4.0-alpine

  database:
    image: mariadb:10.0.20
    ports:
      - "3306:3306"
    env_file:
      - containers/.env
    environment:
      - MYSQL_ROOT_PASSWORD=$${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=$${MYSQL_DATABASE}
      - MYSQL_USER=$${MYSQL_USER}
      - MYSQL_PASSWORD=$${MYSQL_PASSWORD}
    volumes:
      - ./storage/database:/var/lib/mysql
  