version: '3'

services:
    php-fpm:
        build:
            args:
                ENV: "DEV"
        volumes:
            - "./:/var/www/html"
        links:
            - "mailhog:mailhog"
        depends_on:
            - mailhog

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - pcb-web
