version: '3.2'

volumes:
  www:
  db:

services:
  nginx:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
      cache_from:
        - registry.gitlab.com/itsmyfirstday/pcb/nginx:latest
    image: registry.gitlab.com/itsmyfirstday/pcb/nginx
    ports:
      - "80:80"
      # - "443:443"
    restart: unless-stopped
    volumes:
      - www:/var/www/html
    links:
      - php-fpm
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3

  php-fpm:
    build:
      context: .
      dockerfile: containers/php-fpm/Dockerfile
      cache_from:
        - registry.gitlab.com/itsmyfirstday/pcb/php-fpm:latest
    image: registry.gitlab.com/itsmyfirstday/pcb/php-fpm
    restart: unless-stopped
    volumes:
      - www:/var/www/html
    links:
      - redis
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        max_attempts: 3

  redis:
    image: redis:4.0-alpine
    restart: unless-stopped
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3