version: '3'

volumes:
  www:
  db:

services:
  nginx:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
      - "80:80"
      # - "443:443"
    restart: unless-stopped
    volumes:
      - www:/var/www/html
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: containers/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - www:/var/www/html
    links:
      - redis

  redis:
    image: redis:4.0-alpine
    restart: unless-stopped