name: PHP Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Generate localhost certificate
        run:  |
          sudo apt-get install libnss3-tools
          brew install mkcert
          mkcert projectcitybuild.com localhost 127.0.0.1
          mv projectcitybuild.com+2.pem docker/nginx/certs
          mv projectcitybuild.com+2-key.pem docker/nginx/certs

      - name: Build Docker containers
        run:  docker-compose --env-file ./docker/.env.ci up -d

      - name: Check containers are running
        run:  docker-compose logs && docker ps -a

      - name: Overwrite environment file
        run:  docker-compose exec -T php-fpm cp .env.ci .env && docker-compose exec -T php-fpm cat .env

      - name: Validate composer.json and composer.lock
        run:  docker-compose exec -T php-fpm composer validate

#      - name: Get Composer Cache Directory
#        id: composer-cache
#        run: |
#          echo "::set-output name=dir::$(composer config cache-files-dir)"
#      - uses: actions/cache@v1
#        with:
#          path: ${{ steps.composer-cache.outputs.dir }}
#          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-composer-

      - name: Composer dependencies
        run:  docker-compose exec -T php-fpm composer install --no-interaction

      - name: NPM Install
        run:  docker-compose exec -T php-fpm npm ci

      - name: NPM Build
        run:  docker-compose exec -T php-fpm npm run prod

      - name: Generate Key
        run:  docker-compose exec -T php-fpm php artisan key:generate

      - name: Prepare Database
        run:  docker-compose exec -T php-fpm cat .env && docker-compose exec -T php-fpm php artisan migrate

      - name: Larastan
        run:  docker-compose exec -T php-fpm ./vendor/bin/phpstan analyse --memory-limit=1G

      - name: PHPUnit
        run:  docker-compose exec -T php-fpm phpdbg -dmemory_limit=1G -qrr vendor/bin/phpunit --coverage-clover tests/coverage/clover.xml

      - name: Upload coverage
        run:  docker-compose exec -T php-fpm curl -s https://codecov.io/bash | bash -f
